[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "transformer"
version = "0.1"
dependencies = []

[tool.setuptools]
packages = ["transformer"]